pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }

        maven {
            name = 'PaperMC'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }

        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'JoinDate'

include('common',
        'paper',
        'fabric'
)
